import { ABeeZee } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';
import './globals.css'

const inter = ABeeZee({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'MeMo 📝',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
